# Generated by Django 5.0.3 on 2025-08-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_order_cartitem_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
